backend:
  name: github
  repo: iczt/ICZT-Site
  branch: main
  auth_scope: repo
  
media_folder: "images/uploads"
public_folder: "images/uploads"

collections:
  - name: "pages"
    label: "Страницы"
    folder: "content"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Контент", name: "body", widget: "markdown" }
